/* Generated by wayland-scanner 1.24.0 */

#ifndef SWC_SNAP_SERVER_PROTOCOL_H
#define SWC_SNAP_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_swc_snap The swc_snap protocol
 * @section page_ifaces_swc_snap Interfaces
 * - @subpage page_iface_swc_snap - simple screenshot to file descriptor
 */
struct swc_snap;

#ifndef SWC_SNAP_INTERFACE
#define SWC_SNAP_INTERFACE
/**
 * @page page_iface_swc_snap swc_snap
 * @section page_iface_swc_snap_desc Description
 *
 * provides a minimal screenshot capability.
 * @section page_iface_swc_snap_api API
 * See @ref iface_swc_snap.
 */
/**
 * @defgroup iface_swc_snap The swc_snap interface
 *
 * provides a minimal screenshot capability.
 */
extern const struct wl_interface swc_snap_interface;
#endif

/**
 * @ingroup iface_swc_snap
 * @struct swc_snap_interface
 */
struct swc_snap_interface {
	/**
	 * capture screenshot to fd
	 *
	 * captures the current screen and writes it as ppm formay
	 * @param fd file descriptor to write ppm data
	 */
	void (*capture)(struct wl_client *client,
			struct wl_resource *resource,
			int32_t fd);
};


/**
 * @ingroup iface_swc_snap
 */
#define SWC_SNAP_CAPTURE_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
