/* Generated by wayland-scanner 1.24.0 */

#ifndef SWC_SNAP_CLIENT_PROTOCOL_H
#define SWC_SNAP_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_swc_snap The swc_snap protocol
 * @section page_ifaces_swc_snap Interfaces
 * - @subpage page_iface_swc_snap - simple screenshot to file descriptor
 */
struct swc_snap;

#ifndef SWC_SNAP_INTERFACE
#define SWC_SNAP_INTERFACE
/**
 * @page page_iface_swc_snap swc_snap
 * @section page_iface_swc_snap_desc Description
 *
 * provides a minimal screenshot capability.
 * @section page_iface_swc_snap_api API
 * See @ref iface_swc_snap.
 */
/**
 * @defgroup iface_swc_snap The swc_snap interface
 *
 * provides a minimal screenshot capability.
 */
extern const struct wl_interface swc_snap_interface;
#endif

#define SWC_SNAP_CAPTURE 0


/**
 * @ingroup iface_swc_snap
 */
#define SWC_SNAP_CAPTURE_SINCE_VERSION 1

/** @ingroup iface_swc_snap */
static inline void
swc_snap_set_user_data(struct swc_snap *swc_snap, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) swc_snap, user_data);
}

/** @ingroup iface_swc_snap */
static inline void *
swc_snap_get_user_data(struct swc_snap *swc_snap)
{
	return wl_proxy_get_user_data((struct wl_proxy *) swc_snap);
}

static inline uint32_t
swc_snap_get_version(struct swc_snap *swc_snap)
{
	return wl_proxy_get_version((struct wl_proxy *) swc_snap);
}

/** @ingroup iface_swc_snap */
static inline void
swc_snap_destroy(struct swc_snap *swc_snap)
{
	wl_proxy_destroy((struct wl_proxy *) swc_snap);
}

/**
 * @ingroup iface_swc_snap
 *
 * captures the current screen and writes it as ppm formay
 */
static inline void
swc_snap_capture(struct swc_snap *swc_snap, int32_t fd)
{
	wl_proxy_marshal_flags((struct wl_proxy *) swc_snap,
			 SWC_SNAP_CAPTURE, NULL, wl_proxy_get_version((struct wl_proxy *) swc_snap), 0, fd);
}

#ifdef  __cplusplus
}
#endif

#endif
