/* Generated by wayland-scanner 1.24.0 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *swc_snap_types[] = {
	NULL,
};

static const struct wl_message swc_snap_requests[] = {
	{ "capture", "h", swc_snap_types + 0 },
};

WL_EXPORT const struct wl_interface swc_snap_interface = {
	"swc_snap", 1,
	1, swc_snap_requests,
	0, NULL,
};

